url: "http://clementrenaud.com"
permalink: /:path
baseurl: ""
relative_permalinks: false

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - bin

sass:
    sass_dir: scss

description: "Inquiries and experiments about using technologies to produce new forms of writings, spaces and representations."

keywords: "data, visualisation, design, research, China, generative design, network analysis, makers, Shenzhen, topogram, Rhône-Alpes, Lyon, memes, digital writings"

author:
  name: "Clément Renaud"
  tagline: "Algorithmic writings"
  headline: "Data rows & newspapers columns"
  email: "hi@clementrenaud.com"

collections:
    projects:
        output: true
    workshops:
        output: true
