permalink: /:path
baseurl: ""
relative_permalinks: false

gems:
  - jekyll-redirect-from

exclude:
  - bin

sass:
    sass_dir: scss

description: "Inquiries and experiments about using technologies to produce new forms of writings, spaces and representations."


author:
  name: "Clément Renaud"
  tagline: "Algorithmic writings"
  headline: "Data rows & newspapers columns"
  email: "hi@clementrenaud.com"

collections:
    projects:
        output: true
    workshops:
        output: true
