permalink: /:path
baseurl: ""
relative_permalinks: false

gems:
  - jekyll-redirect-from

exclude:
  - bin

sass:
    sass_dir: scss

description: "Clément Renaud is a writer, coder and researcher interested in the transformations of technologies."

author:
  name: "Clément Renaud"
  tagline: "Algorithmic writings"
  headline: "Data rows & newspapers columns"
  email: "hi@clementrenaud.com"

collections:
    projects:
        output: true
    websites:
        output: true
    workshops:
        output: true
    pages:
        output: true
